---
title: "Quick Talks"
output: 
  bookdown::html_document2:
    includes:
      after_body: assets/foot.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(knitr)

```

<style>
  .title{
    display: none;
  }
</style>

<br>

<div class = "blue">

We will be using the [Slack](reference.html) platform to gather questions for the virtual poster presenters and lightning talk presenters. Questions can be submitted all day and long after the meeting is over. The time on the [Agenda](index.html) is reserved for a live Q&A session with the virtual poster presenters and lightning talk presenters, where you can converse and get live feedback and responses immediately from the presenters.

If you are interested in participating in the Q&A, please view the [Slack FAQ Guide](reference.html) for instructions on how to sign up and join (it is free!).

</div>

<br>


## [Middle School Girls' Math and Science Day at MSU](https://www.youtube.com/watch?v=e3sR8EOnPac)

 - **Author**, *Affiliation*
 
 > Brief bio of author or one sentence summary of poster results, objective, or message.
 
<iframe width="800" height="600" src="https://www.youtube.com/embed/e3sR8EOnPac" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

---

<br>

## [Data Visualization for Response](https://www.youtube.com/watch?v=yHahmTU4IAY)

 - **Author**, *Affiliation*
 
 > Brief bio of author or one sentence summary of poster results, objective, or message.

<iframe width="800" height="600" src="https://www.youtube.com/embed/yHahmTU4IAY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

---

<br>

## [Actionable Bioassessment Data: Using Visualization to Bridge the Research - Management Divide](https://www.youtube.com/watch?v=aTru0OrzaEY)

 - **Author**, *Affiliation*
 
 > Brief bio of author or one sentence summary of poster results, objective, or message.

<iframe width="800" height="600" src="https://www.youtube.com/embed/aTru0OrzaEY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

---